### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by GLBB** [mo-han/mf832s-openwrt#1]
大佬你好，刚接触Linux，连不上这个中兴MF832S网卡，请问你这个怎么使用呢

**Comment by mo-han** [comment]
什么操作系统？普通Linux还是OpenWrt/LEDE？

**Comment by GLBB** [comment]
linux系统类的deepin系统，我把你的项目clone下去执行了一下里面的可执行的文件，没起作用，然后因为更多的原因，我目前装回win10了

**Comment by mo-han** [comment]
如果只是想让MF832S连上网的话，只需要`mf832s.chat`这个拨号脚本，找到网卡对应的拨号串口，配合`chat`这个拨号工具。

**Comment by mo-han** [comment]
如果只是想让MF832S连上网的话，只需要`mf832s.chat`这个拨号脚本，找到网卡对应的拨号串口，配合`chat`这个拨号工具。

**Comment by GLBB** [comment]
谢谢了老大
