### ISSUE TITLE
how to config the network on openwrt

### ISSUE THREAD

**Issue by phx135** [mo-han/mf832s-openwrt#2]
Hi,thanks for sharting this awesome to us
I can get it work by your program

but I'm not sure the network file is correct or not
here is my config file,thanks
/etc/config/network (it will auto-genrate eth1 when plug mf832s to usb)

config interface 'wan'
	option proto 'dhcp'
	option ifname 'eth1'

config interface 'wan6'
	option proto 'dhcpv6'
	option reqaddress 'try'
	option reqprefix 'auto'
	option ifname 'eth1'

**Comment by mo-han** [comment]
in `20-mf832s.sh`, there is one line that setup the network interface name:
```shell
NETIF=network.interface.mf832s
```
as you can see i change that specific interface's name to 'mf832s' so i can tell easily, you can change yours into 'mf832s' too, or you could just edit that line as `NETIF=network.interface.eth1`

**Comment by phx135** [comment]
thanks for your respones
I changed the network file to following ,it works too,like before

another question : how can let mf832s worked Automatically after rebooting,I have to re-plug it after rebooting everytime,
I try restart netwotk or usbmode,but it does't work
that's why I ask you the qustion 1
thank you

# cat /etc/openwrt_release
DISTRIB_ID='LEDE'
DISTRIB_RELEASE='17.01-SNAPSHOT'
DISTRIB_REVISION='r4013-981f5f7e40'
DISTRIB_CODENAME='reboot'
DISTRIB_TARGET='ar71xx/generic'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='LEDE Reboot 17.01-SNAPSHOT r4013-981f5f7e40'
DISTRIB_TAINTS='no-all'


config interface 'mf832s'                                                                                                                                                                                     
        option proto 'dhcp'                                                                                                                                                                                   
        option ifname 'eth1'                                                                                                                                                                                  
                                                                                                                                                                                                              
config interface 'mf832s6'                                                                                                                                                                                    
        option proto 'dhcpv6'                                                                                                                                                                                 
        option ifname 'eth1'                                                                                                                                                                                  
        option reqaddress 'try'                                                                                                                                                                               
        option reqprefix 'auto'

**Comment by mo-han** [comment]
In my case it works fine when reboot, without needing to re-plug.

It's driven by usb-hotplug events, unless usb-hotplug is loaded too late while the USB devices are already powered up. However I'm not sure about the reason.

I think you can forget about the real cause, just use a rc.local script to manually start the sequence.

**Comment by phx135** [comment]
I will try it and talk to you later,thank you
by the way,Is this surpport full speed of LTE or only 3G-WAN speed?

**Comment by mo-han** [comment]
Interesting question, while I believe the connection speed is mainly decided by the ISP, the cell signal, the device, and the USB interface. In my case, the MF832S creates a stand-alone USB Ethernet Interface, which is 100M if I recall correctly, however my local LTE provider is under heavy load, the real download speed varies from around 10Mbps to above 100Mbps.

**Comment by phx135** [comment]
the speed is good for me,I like it
I add sleep 15 into 20-mf832s.sh,now it's working on power on without replug it. but not on rebooting
I think maybe it's the fastpath of my openwrt  cause that.

Actually I found another  issue ,I will comment another paragraph

**Comment by phx135** [comment]
I have huawei,E3372H,tianyi-Chinese 4G LTE modem with  based on Qualcomm MDM9600 work with my openwrt router too

but only mf832s can't work with chromecast,I  don't know why ?
I have already add following rule to /etc/firewall.user for DNS redirect

iptables -t nat -A PREROUTING -s 192.168.11.1/24 -p udp --dport 53 -j DNAT --to 192.168.11.1
iptables -t nat -A PREROUTING -s 192.168.11.1/24 -p tcp --dport 53 -j DNAT --to 192.168.11.1


root@Openwrt:~# ip route show
default via 11.1.127.221 dev eth1  proto static  src 11.1.127.220
11.0.0.0/8 dev eth1  proto kernel  scope link  src 11.1.127.220
11.1.127.221 dev eth1  proto static  scope link  src 11.1.127.220
192.168.11.0/24 dev br-lan  proto kernel  scope link  src 192.168.11.1

thanks

**Comment by mo-han** [comment]
I don't know what you're talking about. Why is Chromecast involved? Chromecast is used in LAN area, while LTE modem is for WAN access.

**Comment by phx135** [comment]
Sorry,I may did not explain in clear
I mean I can't cast videos from chromcast to TV by mf832s but google,facebook etcs are ok
same openwrt router,and configration

in otherwords I also can't use google home too

thank you

**Comment by mo-han** [comment]
Well, have you noticed that these two modems are of two totally different ISPs? MF832S can only use SIM card from China Mobile, while "Tianyi" is a brand of China Telecom.

**Comment by phx135** [comment]
Yes it is
I will try figure it out lagter
many thanks for your help 
:clinking_glasses:

**Comment by phx135** [comment]
you are right ,this causeed by ISP
It works when I change to another mobile simcard

thank you
